### ISSUE TITLE
Loaded Cura project not respecting layout when using Spoon Tabs

### ISSUE THREAD

**Issue by PartySausage** [5axes/SpoonAntiWarping#8]
Hi, At the request of Cura Github support [https://github.com/Ultimaker/Cura/issues/18761](https://github.com/Ultimaker/Cura/issues/18761)

Cura Version
5.7.0 Beta 1

Operating System
Windows 10

Printer
Ender 3 S1 Pro

Reproduction steps
Created a project using model & Spoon Anti Warping
Saved & reloaded project

Actual results
Objects apart from one Spoon Tab positioned above the build plate

Expected results
Objects in the project should respect original positions

[Desiccant Box - Box [XL] [HatchBox PLA (Standard), LW-0.4mm, LH-0.2mm, I-25%, T-E.215C, B.65C].zip](https://github.com/5axes/SpoonAntiWarping/files/14804289/Desiccant.Box.-.Box.XL.HatchBox.PLA.Standard.LW-0.4mm.LH-0.2mm.I-25.T-E.215C.B.65C.zip)

**Comment by 5axes** [comment]
Objects in the project should respect original positions.

In version 5.4 the plugin seems to work ... But since this version I have the impression that this problem has appeared. To test but not a high priority in the things I have to do.

**Comment by PartySausage** [comment]
Thanks for the reply. The plugin is still really good to use 😊 just not within saved projects. Hopefully you'll manage to assign some time to it in the future.

**Comment by MariMakes** [comment]
Hey all!

Thanks for the Project File 👍 
This looks like a Cura Bug instead, I'll bring it up to the Cura team to see what they can do to improve it.

Fingers crossed 🤞

**Comment by 5axes** [comment]
Several of my plugins share the same code and therefore present the same problem. The geometries added as Support / Tab / Text or Support Eraser once the project has been saved and reloaded in Cura are no longer in the right position.

I assume that the problem comes from the same code problem, but I haven't found the solution.

Problem seen on :
- Custom Cylinder Support
- Tab Anti Warping
- Tab+ Anti Warping
- Custom Support Eraser
- Name It
- Spoon Anti Warping

The same problem also seems to affect some models of the Calibration Shapes plugin. After reloading a project, the model is no longer at position 0,0,0.

**Initial Position** 

![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/08234786-f6b1-4a1a-a85c-7517de8dfc45)


**Save and Reload Project**

![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/36443e2b-840c-4307-a188-4c82d6a9b12c)

**Comment by 5axes** [comment]
The problem seems to be linked to the backup of files made by Cura. If I load the files into OrcaSlicer or SuperSlicer I get the same problem.
![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/e0b6393c-2da1-4b18-99a5-4229b64d9a86)

![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/b42ea575-163e-474d-b566-18bd05673c22)

**Comment by 5axes** [comment]
Temporary workaround ...

Use Mesh Tool to reset the origin at the center of the mesh for every element. And then it's OK .

![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/7247080e-b5b9-4711-8897-45ff3d841af6)

**Comment by PartySausage** [comment]
Hi @5axes thanks for looking at this & your detective work. 
I created saved & reopened a project file, which had Spoon Tabs & exhibited the layout issue when opened. Then I tried the 'Reset origin to centre of mesh' fix suggested but it didn't alter the layout.
I tried both by selecting all the elements at once then applying the mesh fix & also selecting each element individually & applying the mesh fix to each, but unfortunately neither worked so was wondering is there another step I should also be doing?

**Comment by 5axes** [comment]
'Reset origin to centre of mesh' must be apply before to save the project. After it's too late

**Comment by PartySausage** [comment]
> 'Reset origin to centre of mesh' must be apply before to save the project. After it's too late

Yes that works thanks for the clarification👍

**Comment by 5axes** [comment]
Not totaly Solved with Cura 5.7.2 

Ok additional tab are at the right place .. but if you save and load the project the part is not at the right place.
![image](https://github.com/5axes/SpoonAntiWarping/assets/11015345/86b7f0e5-8211-4c34-a4bf-7eb11604cf7e)
